### ISSUE TITLE
Create tutorial slack channel and refer to it in the tutorial topic

### ISSUE THREAD

**Issue by karengermond** [grafana/writers-toolkit#134]

**Comment by GrafanaWriter** [comment]
Would this be a public channel? If so, we can send them to our public #docs channel. 

If not, then the internal Slack channel already exists, but we wouldn't want to expose that to the public.

**Comment by karengermond** [comment]
Decided to just use the slack channels we have. We say: "If you have an idea for a tutorial you’d like to develop, contact the team. Internal contributors can reach out on Slack and external contributors are welcome to reach us using our [docs@grafana.com](mailto:docs@grafana.com) email."
