### ISSUE TITLE
Add a page about "timeless" docs

### ISSUE THREAD

**Issue by chri2547** [grafana/writers-toolkit#151]
We should add a page about evergeen docs to the toolkit. Google calls it "timeless docs", but we need to stop people from mentioning versions in the docs - that belongs in the What's new, which is a snapshot, the docs should be evergreen

https://raintank-corp.slack.com/archives/D02GKQSFTGR/p1670439821504299)
https://developers.google.com/style/timeless-documentation

**Comment by osg-grafana** [comment]
Let’s avoid the term "evergreen" because it is something that even I need to look up every single time.

**Comment by jdbaldry** [comment]
Closed by #442
