### ISSUE TITLE
Update documentation and tooling workflows page, replace private git links with public git resources

### ISSUE THREAD

**Issue by JStickler** [grafana/writers-toolkit#160]
https://github.com/grafana/writers-toolkit/blob/9e4f708cf74e5c506f510e01f8d1198083524eb9/docs/sources/writing-guide/tooling-and-workflows/_index.md

> This document explains how to use the git command line tool to contribute changes to a Grafana Labs repository. If you are unfamiliar with git, refer to [The Git & Github Bootcamp](https://grafanalabs.udemy.com/course/git-and-github-bootcamp/learn/lecture/24877520%23overview) or [Git and GitHub for Writers](https://grafanalabs.udemy.com/course/git-and-github-for-writers/#overview).

The two linked courses in the Using git section link to courses on https://grafanalabs.udemy.com/ and are not publicly reachable.  We should replace them with resources that are available to any member of the open source community.

**Comment by jdbaldry** [comment]
This wording no longer exists (https://github.com/grafana/writers-toolkit/blob/1285d7e7db8affa1a428a24be9d71a2ca73c0bf3/docs/sources/write/tooling-and-workflows/_index.md?plain=1#L23-L25).
