### ISSUE TITLE
Fix front matter table

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/writers-toolkit#167]
The front matter table has a number of issues:

- It's in HTML instead of Markdown.
- It uses TOML formatting instead of YAML formatting, going against its own guidelines.
- It has weird line breaks that look unbalanced in the new design.

![image](https://user-images.githubusercontent.com/47385188/211003390-5b0e959d-750b-4c47-abd1-933fbb775eaa.png)

It should probably just be a nested list anyways: that would prevent horizontal scroll, avoid weird `<br>`, and naturally mimic the structure of yaml formatting.

@osg-grafana ? Does reformatting it as an unordered list sound OK to you? If so, I'll do it and close this issue.

**Comment by osg-grafana** [comment]
> @osg-grafana ? Does reformatting it as an unordered list sound OK to you? If so, I'll do it and close this issue.

I prefer a list because tables are for data, not layout as a general rule to avoid this kind of thing that is happening here. More arguably sound, a list displays better on mobile.

**Comment by MattDodsonEnglish** [comment]
Well, what's new? I agree completely with Ursula's sense of content.

I'll do this PR next week, I already did some other meta-docs fixes today and I'm meta-tuckered out.
