### ISSUE TITLE
Docs: Show how to embed a file within another file

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#170]
We have some information about how to use shortcodes to include or embed content from one file into another. It would be helpful to _show_ how this is done with a small example that works.

See https://grafana.com/docs/writers-toolkit/writing-guide/shortcodes/.

**Comment by jdbaldry** [comment]
I believe this is covered by https://grafana.com/docs/writers-toolkit/write/reuse-content/reuse-shared-content/
