### ISSUE TITLE
Add semantic line break recommendation

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#21]
See https://sembr.org/.

Relates to #49.

**Comment by jdbaldry** [comment]
I'm in favor of encouraging this because it improves line based diffing which is the default -- and only -- diff setting on GitHub.

**Comment by jdbaldry** [comment]
Locally using `--word-diff` can help.

**Comment by colega** [comment]
If we're not doing this, adding a word somewhere in the middle of a paragraph required modifying the rest of the lines of that paragraph, which makes understanding the difference harder in every environment.

**Comment by colega** [comment]
It's also easier to suggest changes in Github to a single sentence (or block of meaning) when it's one line, rather than when the line contains the end of previous sentence, the sentence you want to change, and the next one. Especially when you also want to suggest changes to previous/next sentence.

**Comment by colega** [comment]
Finally, on wrapping lines: there's no agreement on where we should wrap lines. 

Some people apparently still read diffs on 80x25 terminals, and want their lines wrapped at 72.

```
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. 
```

This looks absurd on a 32 inch 4K screen, so those people wrap the paragraph they add at 120 chars. 

```
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book.

It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently
with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
```

This looks nice to them, but other people working on a 32 inch 4K screen like to split screen (and love split screen diffs), so they just come and reformat previously wrapped at 120 text into 72 columns wrap. But their editor doesn't understand the semantics of the text so it just wraps, without bringing the next lines, ending up in a text wrapped at random columns:

```
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book.

It has survived not only five centuries, but also the leap into.
electronic typesetting, remaining essentially unchanged.
It was popularised in the 1960s with the release of Letraset sheets
containing Lorem Ipsum passages, and more recently
with desktop publishing software like Aldus PageMaker including.
versions of Lorem Ipsum.
```

---

All modern editors, including vim used by the folk at 80x25 terminal, can do word wrapping for their screen, and that's the format Github Markdown expects. So IMO we should do the same in our docs.

**Comment by jdbaldry** [comment]
Thanks for writing that out @colega. I'm in agreement that soft wrapping at screen width is preferable to hard wrapping at fixed column widths. 

I will bring this to the Technical Writer's style council (meeting next Thursday) to get buy in and then we can look to document and codify this practice.

**Comment by Eve832** [comment]
I think that  @colega is making the same argument that I was trying to make in Slack; it sounds to me like an argument _against_ requiring semantic line breaking, though...

**Comment by colega** [comment]
Sorry, @Eve832 I can't see how that's an argument against semantic breaking. IMO nobody should introduce artificial line breaks in text that is intended to be read by humans.

**Comment by Eve832** [comment]
ah, perhaps I meant I was against sembr then. Anyway. I don't like adding extra line breaks is my thing

**Comment by jdbaldry** [comment]
> I don't like adding extra line breaks is my thing

I think there are two ways to interpret that statement.

1. I don't like when extra line breaks are added to wrap content at arbitrary line lengths.
   This is demonstrated in Oleg's first example:
   ```markdown
   Lorem Ipsum is simply dummy text of the printing and typesetting
   industry. Lorem Ipsum has been the industry's standard dummy text ever
   since the 1500s, when an unknown printer took a galley of type and
   scrambled it to make a type specimen book. 
   ```
   
   I think all of us in this thread are in agreement that this is not desirable.

1. I don't like when extra line breaks are introduced in paragraphs of sentences.
   Consider the two paragraphs; the first with semantic line breaks, the second without:
   
   ```markdown
   It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
   It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
   and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
   ```
   
      ```markdown
   It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
   ```
   
   Both result in the same HTMl but the first is more sympathetic to GitHub diff behavior.
   I think it can also be much easier to read and rewrite content written with semantic line breaks.

**Comment by imatwawana** [comment]
I suspect that what @Eve832 is getting at is that this isn't a natural way to write. Most non-technical people are accustomed to using writing tools that automate line-wrapping, so stopping and adding line breaks feels weird and slows you down. I personally find it really awkward when I'm editing a sentence that's been broken at a comma or other form of punctuation besides a period (I realize the rules don't require that, but assuming we use this approach, we also have to set down which rules we are following).

I'm curious, how serious is the line-wrapping issue? From the examples above, I have data points, but I don't have a sense of how serious this actually is if that makes sense. Is this a situation that can be resolved by people just changing a setting vs adding a style rule?

**Comment by imatwawana** [comment]
We came to a preliminary decision in the style meeting to recommend, but not require semantic line breaks at sentence breaks. We'll run a poll of the team on this decision and I'll update this issue with the results.

**Comment by colega** [comment]
Just to clarify, what bothers me is the text wrapped at arbitrary line length and committed as that into files, say 72 chars, or 120, or whatever someone decided is good for _them_. 

This makes it complicated to both edit and see the diff when something changes in the previous lines and a re-wrapping is required.

I don't have such a strong feeling (just a preference) about requiring to add semantic line breaks at sentence breaks. At this point everyone should have an editor that gracefully wraps lines of arbitrary length on the display, but commits them as single lines. Having that is also easy to diff in GitHub, as it highlights word differences within a line.
