### ISSUE TITLE
Docs: Vet documentation from a user-journey lens and apply the changes

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#210]
For user-journey specifics ... we can always create a follow-on PR with a user-journey focus. 

_Originally posted by @osg-grafana in https://github.com/grafana/writers-toolkit/pull/208#discussion_r1138345042_
            
This issue applies originally to the [Documentation structure page](docs/sources/writing-guide/documentation-structure/index.md), but could also be applied to other related content in the writer's toolkit.

**Comment by knylander-grafana** [comment]
Additional items from the original PR #208 : 

From @brendamuir: 
* Is there a better page title than documentation structure? 
* tie content to user journey

**Comment by GrafanaWriter** [comment]
This is complete for now - closing.
