### ISSUE TITLE
Docs: Rewrite alias information and vet example in frontmatter for accuracy

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#212]
https://grafana.com/docs/writers-toolkit/writing-guide/front-matter/#front-matter might need to be corrected or an example be added to reflect the way @jdbaldry is using relative links in aliases.

This section is missing some context: https://grafana.com/docs/writers-toolkit/writing-guide/front-matter/#guidelines.
* What is an alias? (Is it the same thing as a redirect?)
* Where can I find an alias? (Aliases exist in the frontmatter of a documentation topic.)
* When can I remove an alias? (When you move a page to a completely different location, such as from a third-level to a first-level TOC section. <-- Is this an accurate assumption?)
* When should I add an alias? Is there any advantage or disadvantage of adding an alias immediately when I create a new topic?
* How can I test to make sure that my alias works when I am making changes to it? (Open two browser windows, one with the published URL and one with the local URL. Copy the part of the path in question from the "published URL" browser window, and paste it into the "local URL" browser window. Does it redirect to the correct location as expected?)
* Use the rendered URL structure rather than the file-system structure when creating aliases.

**Comment by jdbaldry** [comment]
Existing docs are at https://grafana.com/docs/writers-toolkit/writing-guide/front-matter/#hugo-aliases

**Comment by jdbaldry** [comment]
At the moment we don't remove aliases so I think that documentation can be omitted and this issue can be closed.
