### ISSUE TITLE
Add hackathon proposal for doc template

### ISSUE THREAD

**Issue by josmperez** [grafana/writers-toolkit#220]
Incorporate critical feedback into my doc template proposal from the hackathon and resubmit it.

**Comment by jdbaldry** [comment]
In that case, are you happy for me to close this issue?

Are you aware of the existing Writers' Toolkit templates in https://github.com/grafana/writers-toolkit/tree/main/docs/static/templates?

**Comment by josmperez** [comment]
closing now
