### ISSUE TITLE
Invalid link for Grafana Cloud docs repository

### ISSUE THREAD

**Issue by kuriacka** [grafana/writers-toolkit#243]
On [this page](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-documentation/#find-the-source-repository) is a part that contains link to repository, where are supposed to be stored docs for Grafana Cloud.

`For [Grafana Cloud](https://grafana.com/docs/grafana-cloud/) documentation, most content is managed in the [website repository](https://github.com/grafana/website).`

However [this link](https://github.com/grafana/website) redirects user to non-existing (or private) repository.

If you can point me out to repository that contains docs to Grafana Cloud or suggest any changes to that text, I will gladly submit PR with the change.

**Comment by rukundob451** [comment]
Hey @kuriacka, I faced the same issue as it is related to one I opened earlier today [#274](https://github.com/grafana/writers-toolkit/issues/274)

**Comment by jdbaldry** [comment]
Hey both, sorry for the delay. I missed the original issue and only spotted it when @rukundob451 opened #274.

I really appreciate the willingness of both of you to improve our Grafana Cloud content but, unfortunately, most of the Grafana Cloud content is in the private Grafana website repository. I think I'll need to add a note to the documentation to make it clearer that this repository is private and so the link will 404 for external contributors.

**Comment by rukundob451** [comment]
Thank you for this response @jdbaldry, well basing off this how can I become an internal contributors cause I really have interest in improving Grafana Cloud content and would like to see it go further. I will be glad for a positive response, thank you.

**Comment by rukundob451** [comment]
> At the moment, I don't believe there is any procedure for external contributors to get access to the website repository.
> 
> If you are happy to propose your changes as issues within this repository, I can translate those into patches for the website repository.
> 
> I'm sorry for the inconvenience.

No worries, will do this as suggested @jdbaldry. Thank you.
