### ISSUE TITLE
Link to website repository doesn't work

### ISSUE THREAD

**Issue by rukundob451** [grafana/writers-toolkit#274]
Problem:
- The link to the [website repository](https://github.com/grafana/website) doesn't work under https://grafana.com/docs/writers-toolkit/writing-guide/contribute-documentation/#find-the-source-repository.

Solution:
- The link to the [website repository](https://github.com/grafana/website) should be added correctly under https://grafana.com/docs/writers-toolkit/writing-guide/contribute-documentation/#find-the-source-repository
- A change under the https://github.com/grafana/writers-toolkit/blob/main/docs/sources/writing-guide/contribute-documentation/index.md should be able to fix for that specific website repository.

**Comment by jdbaldry** [comment]
Thank you for bringing this up and also finding an earlier issue referencing the problem. I'm going to close this issue in favor of the original to centralize future updates.
