### ISSUE TITLE
Add examples of absolute arguments in relrefs

### ISSUE THREAD

**Issue by imatwawana** [grafana/writers-toolkit#314]
Per [this comment](https://github.com/grafana/writers-toolkit/pull/311#issuecomment-1708213120) on PR 311

> > Nice, thank you. You can also use absolute arguments to the relref shortcode.

> When you say absolute arguments, do you mean a fully specified URL and/or partial URL? Or something else? If so, it seems a lot faster/easier to just use a regular markdown link than to format a relref.

Indeed, you can specify the file path relative to the linking file or relative to the site root. The latter is typically considered an absolute path.

It is less typing to avoid the shortcode but the reason for using it is build time link checking which makes it easier for you to know that links are broken: https://grafana.com/docs/writers-toolkit/write/references/#build-time-link-checking-with-hugo.
Without the relref shortcode, make docs can't tell you a link is broken. The only way to find that out is to follow the link and make sure it takes you to the destination, either manually, or by waiting for Anne's external crawler. I'd say it's quicker to get the feedback from the build error than to manually click each link.

It additionally encourages us to link directly rather than relying on redirects to avoid broken links. Redirects increases the page load times and negatively affects user experience.

**Comment by GrafanaWriter** [comment]
@imatwawana - can you let me know if this issue is still valid given our move to fully qualified URLs?

**Comment by imatwawana** [comment]
@GrafanaWriter - Looks like @jdbaldry has already started something that addresses this. But if we decide we don't need that content, then this can just be closed.
