### ISSUE TITLE
Add topic to address, "As an engineer, how do I ask for feedback such that that which I receive meets my expectations?"

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#46]
There are many types of feedback, and if our expectations are unaligned, unintended friction can arise.

This issue covers the various types of feedback, as well as the timing of feedback. It also addresses the circumstances where feedback that technical writers provide is not incorporated: if a product needs to go out immediately and the documentation is deemed lower priority for the time being, that also benefits from aligned expectations.

**Comment by jdbaldry** [comment]
Are we still interested in this documentation? Are we seeing the mismatch of expectations in practice?

**Comment by imatwawana** [comment]
I'm not sure if there's a strong need here. I don't think I've really run into this issue. I think we probably have a stronger need for socializing people using the office hours to get help if they don't have an assigned writer. My $0.02.
