### ISSUE TITLE
Grafana.Timeless is too noisy

### ISSUE THREAD

**Issue by jdbaldry** [grafana/writers-toolkit#485]
Although the rule is useful, it regularly produces false positives.

Perhaps it makes more sense as a suggestion to guide writing?

**Comment by jdbaldry** [comment]
- https://github.com/grafana/website/pull/18390/files#r1496433354
- https://github.com/grafana/website/pull/18390/files#r1496433362
- https://github.com/grafana/website/pull/18390/files#r1496433373
- https://github.com/grafana/website/pull/18390/files#r1496433384

**Comment by chri2547** [comment]
@jdbaldry I agree that we should disable this rule and let writers use discretion.
