### ISSUE TITLE
Video related shortcodes should also be documented in the shortcodes page

### ISSUE THREAD

**Issue by jdbaldry** [grafana/writers-toolkit#511]
Presently they are documented in https://grafana.com/docs/writers-toolkit/write/image-guidelines/#where-to-store-media-assets but all other shortcodes are documented in https://grafana.com/docs/writers-toolkit/write/shortcodes/.

Maybe a good use for shared content.

**Comment by GrafanaWriter** [comment]
@jdbaldry - do you want to assign yourself to this issue?
