### ISSUE TITLE
Add a section on information architecture

### ISSUE THREAD

**Issue by jdbaldry** [grafana/writers-toolkit#532]
Remove comment in https://github.com/grafana/writers-toolkit/blob/80f5f402603d801486f4bebe1abc63024a6d4313/docs/sources/structure/_index.md?plain=1#L30-L34

```
<!-- Commenting this paragraph out until we have an actual section on information architecture.

According to STC’s [Information Design and Information Architecture: Why Technical Communicators Should Care About These Fields](https://www.stc.org/intercom/2022/05/information-design-and-information-architecture-why-technical-communicators-should-care-about-these-fields/),
information architecture is "...the practice of organizing, structuring, and labeling information to it’s easy to find, use, and understand..."
-->
```

**Comment by jdbaldry** [comment]
I think this is one for the writers, I found the comment in the Structure page when reviewing the content but I'm not best positioned to write this section.

I believe @knylander-grafana wrote the comment originally.

**Comment by knylander-grafana** [comment]
We had started writing a section on IA and then we ended up with the entire Structure section, which kinda took that place.  The Structure of published content evolved -- I don't know that we need an additional information architecture topic, unless we what to specifically mention it.
