### ISSUE TITLE
Install `prettier` in repo

### ISSUE THREAD

**Issue by osg-grafana** [grafana/writers-toolkit#55]
We should an NPM package configuration file and call it from the Makefilet to run `prettier` on this repository, which can be installed via one of the following commands:

* `npm install --save-dev --save-exact prettier`
* `yarn add --dev --exact prettier`

For more information about installing the `prettier` command, see https://prettier.io/docs/en/install.html.

Relates to #58.

**Comment by jdbaldry** [comment]
Prettier is now enforced in CI and is listed as a dependency in https://github.com/grafana/writers-toolkit/blob/main/package.json#L18.
