### ISSUE TITLE
Add section including visualization topic examples

### ISSUE THREAD

**Issue by jdbaldry** [grafana/writers-toolkit#560]
Add examples when some of these follow the template

```markdown
## Visualization topic examples

Refer to the following topics for visualization topic examples:
```

https://github.com/grafana/writers-toolkit/blob/593cb436173031440d5a385b7f1f435dd471fb73/docs/sources/structure/topic-types/visualization/index.md?plain=1#L127-L131

Remove https://github.com/grafana/writers-toolkit/blob/main/docs/sources/structure/topic-types/visualization/index.md?plain=1#L147 when complete

**Comment by imatwawana** [comment]
Sure yeah. Not sure this needs an issue, but I've assigned it to myself.

**Comment by jdbaldry** [comment]
Bumping this is it came up again as part of my review of the file in https://github.com/grafana/writers-toolkit/pull/724
