### ISSUE TITLE
Grafana.WordList : <ISSUE>

### ISSUE THREAD

**Issue by BeverlyJaneJ** [grafana/writers-toolkit#646]
Please change "Kinesis Data Firehose" as a product name to "Data Firehose". Amazon recently changed it this Spring.

**Comment by jdbaldry** [comment]
Should already be fixed by https://github.com/grafana/writers-toolkit/pull/645

**Comment by jdbaldry** [comment]
Confirmed that the bot no longer posts for Kinesis Data Firehose in https://github.com/grafana/website/pull/19613
