### ISSUE TITLE
Make Grafana icons and logos available to external (and internal) contributors

### ISSUE THREAD

**Issue by chri2547** [grafana/writers-toolkit#66]
This work involves creating a publicly shareable Google slide asset that contains icons and logos found on slides 95 to 98 in https://docs.google.com/presentation/d/1lx5Qy4sCHxD17gG7BnlR4s87N_x84ylSxWY9ydraWro/edit#slide=id.ge5f669b5c3_0_80.

Contributors can use these images when they create diagrams.

**Comment by jdbaldry** [comment]
https://raintank-corp.slack.com/archives/CH34H23HD/p1706679933301989

**Comment by jdbaldry** [comment]
There isn't really anything for public sharing yet.
