### ISSUE TITLE
Document how to contribute to the Vale dictionary

### ISSUE THREAD

**Issue by jdbaldry** [grafana/writers-toolkit#669]
Cover the important parts of the Jsonnet and how the rules and dictionary are regenerated

**Comment by derek-cadzow** [comment]
@jdbaldry Question from our triage this week -- status on this?  Is it something you're planning to assign yourself to?

**Comment by jdbaldry** [comment]
Yeah, let me get this written this week so I can close this.

As a maintainer of this repository I also consider any open issue on this repository implicitly assigned to me in some senses.
I've explicitly assigned myself to this now that I'm planning to work on it, hopefully that helps with your triage :)
