### ISSUE TITLE
Determine if a table section is needed in the toolkit

### ISSUE THREAD

**Issue by imatwawana** [grafana/writers-toolkit#773]
Tables have come up in the style roundtable and the perception is that we need a table section. We should check first if Google's developer guide covers the guidance we need.

**Comment by jdbaldry** [comment]
https://developers.google.com/style/tables

One thing I spotted is that we should discourage the use of `<br>` elements and instead use `<p>` elements to have paragraphs in our tables which makes sense.

**Comment by jdbaldry** [comment]
In https://developers.google.com/style/ui-elements, they use the same formatting rules within the table cells as outside. Namely, that bold is used to highlight UI elements.

**Comment by jdbaldry** [comment]
https://github.com/grafana/writers-toolkit/pull/772/files#diff-dce4785db28c782d8c85d67948ddaed3a01acc26b986f31c08fc02e666f9294fR296 makes sense

**Comment by jdbaldry** [comment]
I think this is covered by the following documentation and PRs:

- https://grafana.com/docs/writers-toolkit/write/markdown-guide/#tables
- https://grafana.com/docs/writers-toolkit/write/style-guide/style-conventions/#bold:~:text=You%20can%20use%20bold%20inline%20with%20other%20prose%20in%20a%20table%2C%20but%20don%E2%80%99t%20use%20bold%20for%20the%20entire%20contents%20of%20a%20cell%2C%20even%20if%20it%E2%80%99s%20a%20UI%20element.%20For%20example%3A
- https://github.com/grafana/writers-toolkit/pull/826
- https://github.com/grafana/writers-toolkit/pull/823
