### ISSUE TITLE
Instead of relying on two hours filter out issues that are not assigned to the project

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/writers-toolkit#866]
e.g. https://github.com/grafana/grafana/issues?q=is%3Aissue%20state%3Aopen%20label%3Atype%2Fdocs%20-project%3Agrafana%2F69

I will add more info on how to fetch those (I assume via graphql as probably the old api rest api does not support "new" projects) later. Need to look it up.

Why?
This will make you miss some issues: https://github.com/grafana/writers-toolkit/blob/main/add-to-docs-project/index.mts#L38 if github actions are down or you have errors or whatever happens.

**Comment by tolzhabayev** [comment]
fyi @jdbaldry - will add more info later

**Comment by jdbaldry** [comment]
Yeah, I think using GraphQL to fetch all the issues will be a nice improvement over iterating over the recently created issues. 

I have buffer with a two hour lookback but a 30 minute schedule but that was definitely a short term workaround until I worked out the appropriate GraphQL call

**Comment by jdbaldry** [comment]
Possibly something like: 

```graphql
query issues($repoCursor: String, $issueCursor: String) {
  organization(login: "grafana") {
    repositories(hasIssuesEnabled: true, after: $repoCursor, first: 100) {
      nodes {
        issues(filterBy: {labels: "type/docs"}, after: $issueCursor, first: 100) {
          nodes {
            id
            projectV2(number: 69) {
              fullDatabaseId
            }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
```

Where I'd need to paginate over both repositories and issues and then filter any that `projectV2` is `null`.

**Comment by tolzhabayev** [comment]
@jdbaldry 

Here is how I would do it:

```
{ 
  search(first: 100, type:ISSUE, query:"org:grafana is:issue state:open label:type/docs -project:grafana/69"){
  issueCount
  pageInfo {
    hasNextPage
    endCursor
  }
  edges {
    node {
      ... on Issue {
        createdAt
        title
        url
        id
      }
    }
  }
}
}
```

then you can also skip [this request](https://github.com/grafana/writers-toolkit/blob/5dfd83cb2b446a54a81608335f8a66ec929619ce/add-to-docs-project/index.mts#L26-L29) as the query above is across the org anyway.

or if you want to narrow it down to some repos you can prepare the repo list and then you would have to use the query above but in a loop and add `repo:grafana/x` - looks like there is quite a backlog (about 200+ issues that were not using the previous github actions - so maybe they should not be added to the project 🤷 ) 

If you want to paginate you can ofc. do it - but I, personally, would go the lazy way and just do 100 at a time. The rate of growth is not that high and with a couple of scheduled runs the backlog will be always lower than 100.

**Comment by jdbaldry** [comment]
Ah the search query makes so much more sense. Thanks! I'll check this out and open a PR

**Comment by jdbaldry** [comment]
> looks like there is quite a backlog of repos that were never added to the docs project, about 200+ issues that were not using the previous github actions - so maybe they should not be added to the project 🤷.

My plan is to make add them all eventually. It was always the intent of the `type/docs` label to have a organization-wide meaning, the workflow just happened to propagate only to some repositories. If the other repos are using that label in a different way, I'll reach out to the teams involved to discuss.
