### ISSUE TITLE
Add deprecation guidelines

### ISSUE THREAD

**Issue by brendamuir** [grafana/writers-toolkit#91]
Once approved, add standard text for docs and deprecation process to our toolkit.

**Comment by osg-grafana** [comment]
Relates to #180.

**Comment by GrafanaWriter** [comment]
https://docs.google.com/document/d/1quxA3ng1y_2jBJicX0H9H8c2oASjCvym3oTRWXmoITU/edit#heading=h.etx9vzsgl2e9

**Comment by GrafanaWriter** [comment]
@Eve832 - Add this to our communication re:release stages?

**Comment by jdbaldry** [comment]
Came up in https://raintank-corp.slack.com/archives/C5PG2JK8W/p1704972913560939

**Comment by brendamuir** [comment]
@jdbaldry I have a funny feeling Kim added this to our wiki

**Comment by jdbaldry** [comment]
Indeed! Great memory :) https://github.com/grafana/technical-documentation/wiki/Release-life-cycle-content-notes#deprecation
