### ISSUE TITLE
Define what a topic is

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/writers-toolkit#92]
The word "topic" appears frequently throughout this repo. Indeed, the "topic" is stated to be the basis for authoring:

> The Documentation Squad at Grafana Labs uses topic-based authoring. Topic-based authoring is a modular approach to content creation where content is structured around topics that can be mixed and reused in different contexts. The topic types we use at Grafana are concept, reference, and task.

But, the docs are missing an explanation of what a "topic" is. Without a definition, the word "topic" becomes a piece of jargon that might be known only to technical writers, and not necessarily all technical writers―perhaps only technical writers familiar with DITA.

Even I'm not 100% sure what a topic is as a unit. I believe that a topic is a single MD file or h1 heading, but I am not sure enough to just make a PR with definition :-).

**Comment by GrafanaWriter** [comment]
We define topic types, and thus topics, here: https://grafana.com/docs/writers-toolkit/structure/topic-types/#topic-types
