### ISSUE TITLE
Update the concept template for writers-toolkit

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/writers-toolkit#97]
@knylander-grafana commented on [Tue Oct 18 2022](https://github.com/grafana/technical-documentation/issues/483)

Review the [concept template](https://github.com/grafana/writers-toolkit/blob/main/docs/static/templates/concept-template.md) for the writer's toolkit and propose updates to make the templates ready for training sessions at offsites in November 2022. 

The goal of these updates is to make the templates easier for users by providing some in-line suggestions or starter phrases. Any changes will align with the writers-toolkit. 

Any updates will be presented to Chris and Brenda for initial review and then to the team at large. 

See also #482

**Comment by osg-grafana** [comment]
Removing myself as assignee because I do not have the bandwidth to work on this at this time.

**Comment by jdbaldry** [comment]
I'm guessing this was done as part of the work discussed in https://github.com/grafana/writers-toolkit/issues/98
