### ISSUE TITLE
Update reference template for writers-toolkit

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/writers-toolkit#98]
@knylander-grafana commented on [Tue Oct 18 2022](https://github.com/grafana/technical-documentation/issues/484)

Review the [reference template](https://github.com/grafana/writers-toolkit/blob/main/docs/static/templates/reference-template.md) for the writer's toolkit and propose updates to make the templates ready for training sessions at offsites in November 2022. 

The goal of these updates is to make the templates easier for users by providing some in-line suggestions or starter phrases. Any changes will align with the writers-toolkit. 

Any updates will be presented to Chris and Brenda for initial review and then to the team at large. 

See also #483 and #482

**Comment by jdbaldry** [comment]
Closing as we are way past the deadline in the issue description.
